name: SkyGenCore
main: supermine.skygencore.Main
author: WindZeus
version: 2.0
api-version: 1.14
load: POSTWORLD
depend:
   - PlaceholderAPI
softdepend:
   - MMOItems   
commands:
   skygencore:
      aliases:
         - core
   kichhoatbooster:
      aliases:
         - khb
   genlist:
   autocompressors:
      aliases:
      - tuchetao
      - autocraft
      - autotrade
      - autoc
      - autochetao   
