name: SkyGenCore
main: grassmine.skygencore.Main
author: HoangPhong
version: 2.0
api-version: 1.18
load: POSTWORLD
depend:
   - PlaceholderAPI
softdepend:
   - MMOItems   
commands:
   skygencore:
      aliases:
         - core
   kichhoatbooster:
      aliases:
         - khb
   genlist:
   autocompressors:
      aliases:
      - tuchetao
      - autocraft
      - autotrade
      - autoc
      - autochetao   
